name: JS Actions

on:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  action:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: hello-action
        uses: ./.github/actions/hello-world

      - name: ha-ha
        uses: ./.github/actions/joke-action
        id: jokes

      - name: create-issue
        uses: ./.github/actions/issue-maker
        with:
          repo-token: ${{secrets.GITHUB_TOKEN}}
          joke: ${{steps.jokes.outputs.joke-output}}

      - name: prs-reply
        uses: ./github/actions/pr-reply
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          author: ${{ github.event.pull_request.user.login }}
          respondableId: ${{ github.event.pull_request.node_id }}
          response: "Thank you @${{ github.event.pull_request.user.login }} for taking out your valuable time in order to contribute to our project. Looking forward for more such amazing contributions :)"
          author: ${{ github.event.pull_request.user.login }}
          #exemptedAuthors: